export class CustomerRecords {
    constructor(
        public date: Date,
        public name?: string,
        public contact?: string,
        public address?: string,
        public m1?: string,
        public m2?: string,
        public m3?: string,
        public m4?: string,
        public m5?: string,
        public m6?: string,
        public m7?: string,
        public m8?: string,
        public m9?: string,
        public m10?: string,
        public m1q?: number,
        public m2q?: number,
        public m3q?: number,
        public m4q?: number,
        public m5q?: number,
        public m6q?: number,
        public m7q?: number,
        public m8q?: number,
        public m9q?: number,
        public m10q?: number,
        public m1p?: number,
        public m2p?: number,
        public m3p?: number,
        public m4p?: number,
        public m5p?: number,
        public m6p?: number,
        public m7p?: number,
        public m8p?: number,
        public m9p?: number,
        public m10p?: number,
        public m1qp?: number,
        public m2qp?: number,
        public m3qp?: number,
        public m4qp?: number,
        public m5qp?: number,
        public m6qp?: number,
        public m7qp?: number,
        public m8qp?: number,
        public m9qp?: number,
        public m10qp?: number,
        public total?: number,
        public paid?: number,
        public dues?: number,
        public comments?: string,
        public descriptions?: string

    ) {

    }
}